const profile = window.PROFILE;
const main = document.querySelector('#main');
const escapeHtml = (value) => String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
const e = escapeHtml;
const safeUrl = (value) => { try { const url = new URL(value); return ['https:', 'http:'].includes(url.protocol) ? url.href : ''; } catch { return ''; } };
const labels = { archive: '교육·디렉팅 아카이브', home: '소개', resume: '이력서', story: '자기소개서', work: '포트폴리오', contact: '연락처' };
document.querySelectorAll('[data-profile]').forEach(el => { el.textContent = profile[el.dataset.profile]; });
document.querySelector('#year').textContent = new Date().getFullYear();

function heading(eyebrow, title, description, action = '') { return `<div class="page-heading"><div><p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p class="lead">${description}</p></div>${action}</div>`; }
function home() {
  return `<section class="hero"><div class="hero-copy"><p class="eyebrow"><span class="blue-dash"></span> A LITTLE ABOUT ME</p><h1>${e(profile.headline[0])}<br><span>${e(profile.headline[1])}</span></h1><p class="hero-description">${e(profile.introduction)}</p><div class="hero-actions"><a class="button primary" href="#resume">이력서 살펴보기 <span>↗</span></a><a class="text-link" href="#work">작업 보러 가기 <span>→</span></a></div></div><div class="profile-card"><div class="profile-card-top"><span>PROFILE / 01</span><span class="profile-spark">✳</span></div><div class="profile-photo"><img src="assets/profile.jpg" alt="정세일 프로필 사진" fetchpriority="high"></div><div class="profile-card-bottom"><strong>${e(profile.name)}</strong><span>${e(profile.role)}</span><div class="profile-tags">${profile.keywords.map(k => `<span>${e(k)}</span>`).join('')}</div></div></div></section>
  ${careerEvolution()}<section class="overview"><div class="section-heading"><div><p class="eyebrow">EXPLORE MY CAREER</p><h2>저를 조금 더 소개할게요.</h2></div><span class="section-note">경험부터 생각까지, 차근차근.</span></div><div class="overview-grid"><a class="overview-card" href="#resume"><div class="card-top"><span class="card-symbol">▤</span><span class="card-index">01</span></div><h3>이력서</h3><p>경력, 학력, 보유 역량을<br>한눈에 살펴보세요.</p><div class="card-bottom"><span>RESUME</span><span>↗</span></div></a><a class="overview-card" href="#story"><div class="card-top"><span class="card-symbol">≡</span><span class="card-index">02</span></div><h3>자기소개서</h3><p>경험 뒤에 담긴 생각과<br>일하는 태도를 소개합니다.</p><div class="card-bottom"><span>MY STORY</span><span>↗</span></div></a><a class="overview-card" href="#work"><div class="card-top"><span class="card-symbol">▦</span><span class="card-index">03</span></div><h3>포트폴리오</h3><p>직접 고민하고 만들어 온<br>작업과 과정을 담았습니다.</p><div class="card-bottom"><span>SELECTED WORK</span><span>↗</span></div></a></div></section>
  <section class="home-values"><p class="eyebrow">MAKE / DIRECT / LEAD / ADAPT</p>${valueCards()}</section><section class="bottom-note"><span class="note-icon">↗</span><div><h2>좋은 기회는, 대화에서 시작되니까요.</h2><p>함께할 기회에 대해 이야기 나누고 싶습니다.</p></div><a href="#contact" class="text-link">연락처 보기 →</a></section>`;
}
function timeline(items) { return '<div class="timeline">'+items.map(item => '<article class="timeline-item"><span class="timeline-date">'+e(item.period)+'</span><div><h3>'+e(item.title)+'</h3><p class="timeline-subtitle">'+e(item.subtitle)+'</p>'+(item.description?'<p>'+e(item.description)+'</p>':'')+(item.sections||[]).map(section=>'<section class="experience-group"><h4>'+e(section.title)+'</h4><ul>'+section.items.map(text=>'<li>'+e(text)+'</li>').join('')+'</ul></section>').join('')+(item.closing?'<p class="experience-closing">'+e(item.closing)+'</p>':'')+(item.note?'<p class="experience-note">'+e(item.note)+'</p>':'')+'</div></article>').join('')+'</div>'; }
function resume() { return `${heading('MY RESUME', '경험을 한눈에.', '지금까지 걸어온 길과, 앞으로 활용할 수 있는 역량입니다.', '<button class="button secondary" id="print-resume">인쇄 / PDF 저장 ↗</button>')}<section class="resume-intro panel"><div class="resume-identity"><img class="resume-photo" src="assets/profile.jpg" alt="정세일 프로필 사진"><div><span class="eyebrow">PROFILE</span><h2>${e(profile.name)}</h2><p class="role">${e(profile.role)}</p><p class="career-duration">${e(profile.careerSummary)}</p></div></div><p>${e(profile.about)}</p></section><section class="document-section"><h2><span>01</span>경력 사항</h2>${timeline(profile.experience)}</section><section class="document-section"><h2><span>02</span>학력 및 교육</h2>${timeline(profile.education)}</section><section class="document-section"><h2><span>03</span>보유 역량</h2><div class="skills-grid">${profile.skills.map(skill => `<article class="panel skill"><h3>${e(skill.name)}</h3><p>${e(skill.detail)}</p></article>`).join('')}</div></section>${softwareSection()}<section class="document-section"><h2><span>${profile.software?.length ? '05' : '04'}</span>자격 사항</h2>${timeline(profile.certifications)}</section>`; }
function softwareSection() { if (!profile.software?.length) return ''; return `<section class="document-section"><h2><span>04</span>사용 프로그램</h2><div class="software-grid">${profile.software.map(tool => `<article class="panel software-card"><h3>${e(tool.name)}</h3><p>${e(tool.tasks)}</p></article>`).join('')}</div></section>`; }
function story() { return `${heading('MY STORY', '경험을 실무의 기여로 연결합니다.', '영상 제작과 피드백, 협업 경험을 바탕으로 팀에서 맡을 수 있는 역할과 일하는 방식을 소개합니다.')}<p class="draft-notice">${profile.storyIsDraft ? '이력서의 경력 사실을 바탕으로 구성한 자기소개서 초안입니다.' : ''}</p><div class="story-layout"><nav class="story-index" aria-label="자기소개서 항목">${profile.stories.map(s => `<a href="#story/${s.number}"><span>${e(s.number)}</span>${e(s.summary)}</a>`).join('')}</nav><div class="story-articles">${profile.stories.map(s => `<article class="story-article panel" id="story-${e(s.number)}"><p class="eyebrow">${e(s.number)} / ${e(s.tag)}</p><h2>${e(s.title)}</h2><p class="story-body">${e(s.body)}</p></article>`).join('')}</div></div>`; }
function work(category = '전체') { return renderWorkPage(category); }
function project(index) { const p = profile.projects[index]; if (!p) return work(); const url = safeUrl(p.url); return `<a class="back-link" href="#work">← 포트폴리오 목록</a>${heading(e(p.category).toUpperCase(), e(p.title), e(p.description))}<div class="project-facts panel"><div><span>${p.videoIds?.length ? 'PROJECT TYPE' : 'PERIOD'}</span><strong>${e(p.year)}</strong></div><div><span>MY ROLE</span><strong>${e(p.role)}</strong></div><div><span>CATEGORY</span><strong>${e(p.category)}</strong></div></div>${projectVideoWorks(p)}<section class="project-detail panel">${p.purpose ? `<p class="eyebrow">OVERVIEW</p><h2>프로젝트 목적</h2><p>${e(p.purpose)}</p>` : ''}${p.intent ? `<p class="eyebrow">INTENT</p><h2>기획 의도</h2><p>${e(p.intent)}</p>` : ''}<p class="eyebrow">PROCESS</p><h2>어떤 작업을 맡았나요?</h2><p>${e(p.process)}</p><p class="eyebrow">CONTRIBUTION</p><h2>무엇을 만들었나요?</h2><p>${e(p.result)}</p>${p.point ? `<p class="eyebrow">POINT</p><h2>경험의 핵심</h2><p>${e(p.point)}</p>` : ''}${p.mentoringLink ? '<a class="button secondary" href="#work/mentoring">교육·디렉팅 작품 보기 ↗</a>' : ''}${url ? `<a class="button primary" href="${e(url)}" target="_blank" rel="noopener noreferrer">프로젝트 열기 ↗</a>` : p.videoIds?.length || p.mentoringLink ? '' : '<p class="empty-note">프로젝트 링크는 아직 등록되지 않았습니다.</p>'}</section>`; }
function contact() { return `${heading('LET’S CONNECT', '다음 이야기를 함께.', '채용 및 협업에 관한 연락을 기다립니다.')}<section class="contact-panel panel"><span class="eyebrow">CONTACT INFORMATION</span><h2>${e(profile.name)}</h2><p>${e(profile.role)}</p><div class="contact-row"><span>이메일</span>${profile.email ? `<a href="mailto:${e(profile.email)}">${e(profile.email)} ↗</a>` : '<span>이메일 등록 전</span>'}</div><div class="contact-row"><span>활동 지역</span><span>${e(profile.location)}</span></div>${profile.isTemplate ? '<p class="empty-note">현재는 템플릿입니다. 실제 연락처는 아직 등록되지 않았습니다.</p>' : ''}</section>`; }
function render() { const [rawPage, arg] = location.hash.slice(1).split('/'); const page = rawPage || 'home'; const active = ['project', 'motion', 'archive', 'video'].includes(page) ? 'work' : page; const routes = { home, resume, story, work, contact, archive: () => renderMotionArchive(arg) }; main.innerHTML = page === 'video' ? personalVideoDetail(arg) : page === 'motion' ? motionDetail(arg) : page === 'project' ? project(Number(arg)) : (routes[page] || home)(); document.querySelector('#breadcrumb').textContent = labels[active] || '소개'; document.title = `${labels[active] || '소개'} — 정세일 | Career Folio`; document.querySelectorAll('[data-nav]').forEach(a => { const current = a.dataset.nav === active; a.classList.toggle('active', current); if(current) a.setAttribute('aria-current','page'); else a.removeAttribute('aria-current'); }); document.querySelector('#print-resume')?.addEventListener('click', () => window.print()); if (page === 'work' && arg) document.getElementById(`work-${arg}`)?.scrollIntoView({block: 'start'}); else if (page === 'story' && arg) document.getElementById(`story-${arg}`)?.scrollIntoView({block: 'start'}); else window.scrollTo(0,0); }
main.addEventListener('click', event => { const button = event.target.closest('[data-filter]'); if (!button) return; main.innerHTML = work(button.dataset.filter); [...main.querySelectorAll('[data-filter]')].find(b => b.dataset.filter === button.dataset.filter)?.focus(); });
window.addEventListener('hashchange', () => { render(); main.focus({preventScroll: true}); });
render();

