// Render the same homepage into HTML for crawlers and pre-JavaScript visitors.
// Run after changing homepage content: node build-static.cjs
const fs=require('node:fs');
const vm=require('node:vm');
const path=require('node:path');
const nodes=new Map();
function node(selector){if(!nodes.has(selector))nodes.set(selector,{innerHTML:'',textContent:'',addEventListener(){},focus(){},classList:{toggle(){}},setAttribute(){},removeAttribute(){}});return nodes.get(selector);}
const context={console,URL,location:{hash:'#home'},document:{querySelector:node,querySelectorAll:()=>[],addEventListener(){},getElementById:()=>null},window:{addEventListener(){},scrollTo(){},print(){}}};
vm.createContext(context);
for(const file of ['profile.js','motion-gallery-data.js','motion-gallery.js','career-sections.js','app.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,file),'utf8'),context,{filename:file});
const rendered=node('#main').innerHTML;
if(!rendered.includes('제작의 전 과정을 보는 사람이 되었습니다.'))throw Error('Homepage render failed');
const file=path.join(__dirname,'index.html');
let html=fs.readFileSync(file,'utf8');
html=html.replace(/(<main id="main" tabindex="-1">)[\s\S]*?(<\/main>)/,(_,open,close)=>open+'\n<!-- Generated by build-static.cjs -->\n'+rendered+'\n'+close);
fs.writeFileSync(file,html.trimEnd()+'\n');
console.log('Static homepage updated');
